apiVersion: v1
kind: Service
metadata:
  name: cortexia-qdrant
  namespace: cortexia
  labels:
    app: cortexia-qdrant
spec:
  ports:
    - port: 6333
      name: http
    - port: 6334
      name: grpc
  clusterIP: None
  selector:
    app: cortexia-qdrant
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cortexia-qdrant
  namespace: cortexia
spec:
  serviceName: "cortexia-qdrant"
  replicas: 1
  selector:
    matchLabels:
      app: cortexia-qdrant
  template:
    metadata:
      labels:
        app: cortexia-qdrant
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:v1.8.3
          ports:
            - containerPort: 6333
              name: http
            - containerPort: 6334
              name: grpc
          volumeMounts:
            - name: qdrant-data
              mountPath: /qdrant/storage
  volumeClaimTemplates:
    - metadata:
        name: qdrant-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
